[parity]
chain = "dev"
unlock = ["0x00a329c0648769a73afac7f9381e08fb43dbea72"]

[network]
port = 30303
nat = "any"

[rpc]
disable = false
port = 8545
interface = "all"
cors = "*"
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore"]
hosts = ["all"]

[websockets]
disable = false
port = 8546
interface = "all"
origins = ["all"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore"]
hosts = ["all"]

[dapps]
disable = true

[ipc]
disable = false
path = "/ipc/jsonrpc.ipc"
apis = ["web3", "eth", "net", "parity", "parity_accounts", "personal", "traces", "rpc", "secretstore"]
